### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'major'

### ISSUE THREAD

**Issue by tansydev** [orientechnologies/pyorient#1]
Hi
I'm using python2.6.6 on centos6.6.

after install pyorient, i found error message.

>>> client = pyorient.OrientDB("localhost",2424)
>>> session_id = client.connect("admin","admin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyorient/orient.py", line 209, in connect
    .prepare(args).send().fetch_response()
  File "pyorient/messages/connection.py", line 54, in prepare
    return super( ConnectMessage, self ).prepare()
  File "pyorient/messages/base.py", line 119, in prepare
    self._encode_field( x ) for x in self._fields_definition
  File "pyorient/messages/base.py", line 119, in <genexpr>
    self._encode_field( x ) for x in self._fields_definition
  File "pyorient/messages/base.py", line 279, in _encode_field
    if sys.version_info.major >= 3:
AttributeError: 'tuple' object has no attribute 'major'

**Comment by tansydev** [comment]
Hi. 
I think pyorient supports only python 3.X.
because, memoryview(buf) in orient.py supports only python3.x.
is it correct?

**Comment by Ostico** [comment]
Hi @tansydev ,
Pyorient at moment supports only python 2.7.x-3.
I think this issue depends on the package sys.

In python < 2.7 , sys.version_info was a tuple, in python >= 2.7 it is a dict.

**Comment by tansydev** [comment]
hi
thank you for your reply.
i think so that my python version 2.6.6.
please, close my issue😀

2015년 5월 3일 (일) 오후 10:20, Domenico Lupinetti <notifications@github.com>님이
작성:

**Comment by Ostico** [comment]
Moved here:
https://github.com/mogui/pyorient/issues/67
