### ISSUE TITLE
OrientDB 2.2 BETA not supported yet

### ISSUE THREAD

**Issue by kaYcee** [orientechnologies/pyorient#11]
Protocol version only up to 32 supported (new 2.2 beta uses 33). If manually changed in constants.py receiving error "pyorient.exceptions.PyOrientSecurityAccessException: com.orientechnologies.orient.core.exception.OSecurityAccessException - User or password not valid for database" - regardless of the username. Has apparently to do with the recently introduced encrypted user/password management.

**Comment by ArielleA** [comment]
Version 36 now, 2.2.0 rc1. Is there a protocol document that can be used by the community to submit patches?

**Comment by Ostico** [comment]
No @ArielleA, there is not at the moment.
I already submitted an issue to Orient team.

**Comment by Ostico** [comment]
Now documentation seems updated now. This week i will make the upgrade.
