### ISSUE TITLE
Graph reserved words(in, out)

### ISSUE THREAD

**Issue by mwalkowski** [orientechnologies/pyorient#12]
Why words "in" and "out" are reserved in graph.py (line: 663)?
I think they should be permitted, because referring to documentation http://orientdb.com/orientdb-using-schemas-with-graphs-part-1/.
I should be albe to create these properties with ogm.
BR
Michal

**Comment by TropicalPenguin** [comment]
Hi, I did that because of orientechnologies/orientdb/issues/4684. Perhaps graph.py should be smarter about which it allows and which it does not; what do you think?

**Comment by Ostico** [comment]
Hi,
can i close this?
