### ISSUE TITLE
create abstract classes using the OGM

### ISSUE THREAD

**Issue by creisle** [orientechnologies/pyorient#19]
Is it possible to create abstract classes using the OGM?

**Comment by decebal** [comment]
+1

**Comment by TropicalPenguin** [comment]
Hm, I guess I should be following this repo's issues. Not yet, but I've started pondering elegant ways to achieve this.

**Comment by TropicalPenguin** [comment]
Some [notes on syntax](https://github.com/mogui/pyorient/issues/239).

@lvca: I suppose this issue can be closed when this repo is sync'd with mogui/pyorient.

**Comment by Ostico** [comment]
Close.
