### ISSUE TITLE
Change vertex class

### ISSUE THREAD

**Issue by decebal** [orientechnologies/pyorient#22]
Is there any way that a vertex 's class can be changed / renamed ?

**Comment by Ostico** [comment]
Hi @decebal ,

refer to this:
https://orientdb.com/docs/2.1/SQL-Alter-Class.html

**Comment by decebal** [comment]
Thanks Ostico, also looked at `move`, I was hoping to find an ogm abstraction of that. As a workaround I am executing a move command in my code (Moving the node from one class to another)
