### ISSUE TITLE
Saving vertices and nodes fails with read-only properties

### ISSUE THREAD

**Issue by FalFire** [orientechnologies/pyorient#25]
When using the OGM, calling instance.save() on an instance of a vertex or relationship class fails when some of the properties are declared as read-only in OrientDB, even when they are declared read-only on the model fields as well. This appears to be due to save_element of class ogm.graph.Graph calling props_to_db which happily returns all properties.

**Comment by TropicalPenguin** [comment]
[Resolved](https://github.com/mogui/pyorient/issues/238). Thanks for the diagnosis!

Once synced with mogui/pyorient, this issue can be closed too.

**Comment by Ostico** [comment]
Tnx @TropicalPenguin .
Closing.
