### ISSUE TITLE
pyorient does not connect to orientdb 2.1-rc*, Protocol version 30 is not yet supported

### ISSUE THREAD

**Issue by zhuobao** [orientechnologies/pyorient#3]
connection from pyorient to community orientdb 2.1-rc* fails. Below is the exception:

PyOrientWrongProtocolVersionException     Traceback (most recent call last)
<ipython-input-2-10e1b130a19a> in <module>()
      1 ## build python <----> orientDB connections
      2 client=po.OrientDB("localhost", 2424)
----> 3 session_id=client.connect("root", "Butter06")

/home/zbao/anaconda/lib/python2.7/site-packages/pyorient/orient.pyc in connect(self, *args)
    207 
    208     def connect(self, *args):
--> 209         return self.get_message("ConnectMessage") \
    210             .prepare(args).send().fetch_response()
    211 

/home/zbao/anaconda/lib/python2.7/site-packages/pyorient/orient.pyc in get_message(self, command)
    344                 else:
    345                     token = self._auth_token
--> 346                 return _Message(self._connection)\
    347                     .set_session_token( token )
    348         except KeyError as e:

/home/zbao/anaconda/lib/python2.7/site-packages/pyorient/messages/connection.pyc in __init__(self, _orient_socket)
     16 
     17     def __init__(self, _orient_socket):
---> 18         super( ConnectMessage, self ).__init__(_orient_socket)
     19 
     20         self._user = ''

/home/zbao/anaconda/lib/python2.7/site-packages/pyorient/messages/base.pyc in __init__(self, sock)
     38         :type sock: OrientSocket
     39         """
---> 40         sock.get_connection()
     41         self._orientSocket = sock
     42         self._protocol = self._orientSocket.protocol

/home/zbao/anaconda/lib/python2.7/site-packages/pyorient/orient.pyc in get_connection(self)
     38     def get_connection(self):
     39         if not self.connected:
---> 40             self.connect()
     41 
     42         return self._socket

/home/zbao/anaconda/lib/python2.7/site-packages/pyorient/orient.pyc in connect(self)
     61                 raise PyOrientWrongProtocolVersionException(
     62                     "Protocol version " + str(self.protocol) +
---> 63                     " is not supported yet by this client.", [])
     64             self.connected = True
     65         except socket.error as e:

PyOrientWrongProtocolVersionException: Protocol version 30 is not supported yet by this client.

**Comment by zhuobao** [comment]
when is the proper timeline rolling out pyorient support to 2.1?

**Comment by sebastiandev** [comment]
@zhuobao I think is working now. Im using it.
