### ISSUE TITLE
Protocol version 32 is not supported yet by this client.

### ISSUE THREAD

**Issue by zero-** [orientechnologies/pyorient#9]
Getting `Protocol version 32 is not supported yet by this client.` and I'm running 2.1.5.

Any ETA support for newer protocols?

**Comment by lashex** [comment]
I just started trying to poke around with OrientDB and I am also getting this when running 2.1.8. Specifically, `pyorient.exceptions.PyOrientWrongProtocolVersionException: Protocol version 32 is not supported yet` by this client.

**Comment by Ostico** [comment]
Hi guys, protocol 32 is already supported by pyorient. 

The issue is in the pypi repository.

I apologize for this. Please, for now clone the github repository untill pypi will be fixed.

It works.
